### ISSUE TITLE
Problem of box-sizing

### ISSUE THREAD

**Issue by guoyunhe** [ThisIsDallas/Simple-Grid#29]
Simple-Grid set box-sizing of * as border-box. But I don't need it in other place. If I add it to my site, it will force the whole site change the look and may cause unexpected problem.

I suggest only to apply box-sizing on those elements that are related to Simple Grid.

**Comment by josephj** [comment]
+1

**Comment by Paveltarno** [comment]
+1

**Comment by slmsmsk** [comment]
+1

**Comment by starock** [comment]
+1

**Comment by ThisIsDallas** [comment]
This is fixed.
